# Generated by Django 3.2.5 on 2021-07-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job',
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.job'),
            preserve_default=False,
        ),
    ]
