# Generated by Django 3.2.5 on 2021-07-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210713_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
